.PHONY: test docs


build :
	./node_modules/.bin/coffee harness/build


cli :
	./node_modules/.bin/coffee -c --bare bin/cli.coffee
	rm bin/cli.js
	echo '#!/usr/bin/env node' > bin/cli.js
	cat bin/cli.coffee | ./node_modules/.bin/coffee -sc --bare >> bin/cli.js

#
# #### `make deploy OUTPUT=/absolute/path/to/rails/app`
#
# ###### "Deploy" in the sense of copying built assets into another local app repository
#
deploy : release
	./node_modules/.bin/coffee harness/deploy
# ---


#
# #### `make dev`
#
# - Primary development task
# - Start up a file watcher to run `make build` each time a source file changes.
# - Start up a web server to respond to mock API requests at `localhost:8080`.
# - Start up a `livereload` instance to refresh the browser each time a file changes (Chrome extension required).
#
dev :
	./node_modules/.bin/coffee harness/start development-server
# ---


#
# #### `make docs`
#
# ###### Generate documentation from inline comments in the source CoffeeScript files.
#
docs :
	./node_modules/.bin/groc -e "./node_modules/**/*" "./**/*.coffee" README.md
# ---


#
# #### `make itest`
#
# - Create a fresh build and start up the development server at `localhost:8081`.
# - Use [casper.js](http://casperjs.org/) to browse the app headlessly and run integration tests.
# - Simulate clicking, form filling, and URL manipulation.
# - Assert cookie values, URL values, and UI values.
#
itest : build
	./node_modules/.bin/coffee harness/start integration-tests
# ---


#
# #### `make test`
#
# - Create a fresh build
# - Start up a testem instance that reruns all tests each time a source or test file changes.
# - Tests are run automatically in all browsers currently opened to `localhost:7357`.
#
test : build
	./node_modules/.bin/testem -f harness/testem.json -l PhantomJS app/test
# ---


release :
	NODE_ENV=release make build
	echo "//Generated by https://github.com/todoubled/harness"|cat - ./app/public/$PROJECT_PREFIX.js > /tmp/out && mv /tmp/out ./app/public/$PROJECT_PREFIX.js
	echo "/*Generated by https://github.com/todoubled/harness*/"|cat - ./app/public/$PROJECT_PREFIX.css > /tmp/out && mv /tmp/out ./app/public/$PROJECT_PREFIX.css


watch :
	./node_modules/.bin/watchman app/source "make build"


webserver :
	./node_modules/.bin/coffee harness/server
