.PHONY: test docs

build :
	./harness/env.sh coffee harness/build

deploy :
	make release
	./harness/env.sh coffee harness/deploy

docs :
	./harness/env.sh groc -e "./node_modules/**/*" "./**/*.coffee" README.md

install :
	./harness/env.sh npm install

itest :
	make build
	./harness/env.sh coffee harness/start integration-tests

release :
	NODE_ENV=release make build
	echo "//Generated by https://github.groupondev.com/gift/gift-finder"|cat - ./app/public/gift-finder.js > /tmp/out && mv /tmp/out ./app/public/gift-finder.js
	echo "/*Generated by https://github.groupondev.com/gift/gift-finder*/"|cat - ./app/public/gift-finder.css > /tmp/out && mv /tmp/out ./app/public/gift-finder.css

server :
	./harness/env.sh coffee harness/start development-server

test :
	make build
	./harness/env.sh testem -f harness/testem.json app/test

watch :
	./harness/env.sh watchman app/src "make build"

webserver :
	./harness/env.sh coffee harness/server
